### ISSUE TITLE
Suggestion: Consider removing Bootstrap and jQuery

### ISSUE THREAD

**Issue by njoguamos** [andersonmadeira/vue-laravel-element-boilerplate#3]
The whole point of the project (from my understanding) is to be a [Laravel](https://laravel.com) boilerplate for a [element-ui](http://element.eleme.io/#/en-US).  We could consider making the following changes.

1. Remove bootstrap (sass and js) or make them optional
2. Remove jQuery (a bootstrap dependency)

**Comment by amadeirado** [comment]
Your considerations are indeed valid.
